# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
    ]
