# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
