# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
    ]
