# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('events', '0007_remove_event_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='blog.Blog', verbose_name='\u0411\u043b\u043e\u0433'),
            preserve_default=False,
        ),
    ]
