# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160420_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': '\u0422\u044d\u0433', 'verbose_name_plural': '\u0422\u044d\u0433\u0438'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='event',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='blog.Blog', verbose_name='\u0411\u043b\u043e\u0433'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='events.Tag'),
        ),
    ]
